//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int AgentID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int OrdersStatusID { get; set; }
        public bool PrepaymentReceived { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual OrdersStatu OrdersStatu { get; set; }
    }
}
