//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public int AccessLogID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Location { get; set; }
    }
}
