//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeesID { get; set; }
        public int DepartmentID { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public byte[] PassportData { get; set; }
        public byte[] BankDetails { get; set; }
        public Nullable<bool> FamilyStatus { get; set; }
        public Nullable<bool> HealthIssues { get; set; }
        public Nullable<int> SpecializationID { get; set; }
    }
}
