//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.SupplyHistories = new HashSet<SupplyHistory>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int MaterialID { get; set; }
        public string Name { get; set; }
        public int MaterialTypeID { get; set; }
        public Nullable<int> SuppliersID { get; set; }
        public Nullable<int> PackageQuantity { get; set; }
        public int MaterialUnitTypeID { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public Nullable<int> MinQuantity { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual MaterialUnitType MaterialUnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyHistory> SupplyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
