//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyHistory
    {
        public int SupplyHistoryID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> QualityRating { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
