//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Materials = new HashSet<Material>();
        }
    
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public Nullable<int> SupplierTypeID { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        public Nullable<int> SupplyHistoryID { get; set; }
        public Nullable<int> MaterialsSuppliersID { get; set; }
    
        public virtual BusinessType BusinessType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Materials { get; set; }
    }
}
